name: YouTube Booster Run

on:
  schedule:
    - cron: '0 * * * *' # Se lance automatiquement toutes les heures
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install selenium
      - name: Run Bot
        run: python bot_v1.py
